name: testing

on: push
#  push:
#    branches:
#      - '**'
#      - '!master'



jobs:

  validate:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Validate code
        run: echo "HELLOOOOOOO"