name: testing

on:
#  push:
#    branches:
#      - '**'
#      - '!master'

#env:

jobs:

  validate:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Validate code
        run: echo "HELLOOOOOOO"